i2v: true
training_target: high_noise
model_name: Wan2.2-I2V-A14B
real_name: Wan2.2-I2V-A14B/high_noise_model
fake_name: Wan2.2-I2V-A14B/high_noise_model
generator_type: bidirectional
generator_name: Wan2.2-I2V-A14B/high_noise_model
text_encoder_cpu_offload: true
denoising_step_list:
- 1000
- 875
- 750
- 625
boundary_step: 500
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 3.5
denoising_loss_type: flow
mixed_precision: true
seed: 0
mlflow_tracking_uri: ""
mlflow_experiment: "wan22_i2v_dmd"
mlflow_run_name: ""
lr: 2.0e-06
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
data_type: text_folder
data_path: /data/mydataset/output_lmdb/
data_max_count: 200000
batch_size: 1
total_batch_size: 64
log_iters: 200
negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
dfake_gen_update_ratio: 5
image_or_video_shape:
- 1
- 21
- 16
- 104
- 60
distribution_loss: dmd
trainer: score_distillation
gradient_checkpointing: true
num_frame_per_block: 3
load_raw_video: false
model_kwargs:
  timestep_shift: 5.0
